// 校验首页改版进产物（中文按 \uXXXX 转义检索）
const fs = require('fs')
const esc = s => s.split('').map(c => c.charCodeAt(0) > 255 ? '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0') : c).join('')
const homeJs = fs.readFileSync('dist/pages/home/home.js', 'utf8')
const homeWxml = fs.readFileSync('dist/pages/home/home.wxml', 'utf8')
const homeWxss = fs.readFileSync('dist/pages/home/home.wxss', 'utf8')
const idxJs = fs.readFileSync('dist/pages/index/index.js', 'utf8')
const commonJs = fs.readFileSync('dist/common.js', 'utf8')

console.log('--- home.wxml 结构 ---')
;['精选专题', '热门旅游城市', '最近行程', '查看详细行程', '还没有行程'].forEach(k => console.log(k, homeWxml.includes(k) ? 'OK' : 'MISSING'))
console.log('--- home.js 数据/逻辑 ---')
;['在南京，时间是可以摸到的', '倒计时', 'city=', 'tripId='].forEach(k => console.log(k, homeJs.includes(esc(k)) || homeJs.includes(k) ? 'OK' : 'MISSING'))
console.log('--- 图片资源打进产物 ---')
const imgs = fs.readdirSync('dist/assets/home')
imgs.forEach(f => console.log(f, Math.round(fs.statSync('dist/assets/home/' + f).size / 1024) + 'KB'))
console.log('--- 城市预填（index.js）---')
console.log('city 参数读取', idxJs.includes('city') && idxJs.includes('destinationCity') ? 'OK' : 'MISSING')
console.log('--- mock 列表扩展字段 ---')
console.log('startDate', commonJs.includes('startDate') ? 'OK' : 'MISSING')
console.log('--- 新配色 ---')
console.log('#48a999', homeWxss.toLowerCase().includes('#48a999') ? 'OK' : 'MISSING')
